/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/auth/index.vue')['default']
    AuthCaptcha: typeof import('./src/components/auth/AuthCaptcha.vue')['default']
    AuthImage: typeof import('./src/components/auth/AuthImage.vue')['default']
    AuthLoginForm: typeof import('./src/components/auth/AuthLoginForm.vue')['default']
    AuthRegisterMember: typeof import('./src/components/auth/AuthRegisterMember.vue')['default']
    AuthRegisterMemberForm: typeof import('./src/components/auth/AuthRegisterMemberForm.vue')['default']
    AuthRegstMember: typeof import('./src/components/auth/AuthRegstMember.vue')['default']
    AuthTitle: typeof import('./src/components/auth/AuthTitle.vue')['default']
    Bottom: typeof import('./src/components/footer/bottom/bottom.vue')['default']
    Breadcrumb: typeof import('./src/components/footer/breadcrumb/index.vue')['default']
    Captcha: typeof import('./src/components/auth/Captcha.vue')['default']
    copy: typeof import('./src/components/auth/AuthLoginForm copy.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Footer1: typeof import('./src/components/Footer1.vue')['default']
    FooterBottom: typeof import('./src/components/footer/FooterBottom.vue')['default']
    FooterBreadcrumb: typeof import('./src/components/footer/FooterBreadcrumb.vue')['default']
    FooterSocialMedia: typeof import('./src/components/footer/FooterSocialMedia.vue')['default']
    FooterTopIcon: typeof import('./src/components/footer/FooterTopIcon.vue')['default']
    FooterTopLeft: typeof import('./src/components/footer/FooterTopLeft.vue')['default']
    FooterTopTitell: typeof import('./src/components/footer/FooterTopTitell.vue')['default']
    FooterTopTitle: typeof import('./src/components/footer/FooterTopTitle.vue')['default']
    GlobalComponents: typeof import('./src/components/GlobalComponents/index.vue')['default']
    LeftImage: typeof import('./src/components/auth/LeftImage.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialMedia: typeof import('./src/components/footer/socialMedia/index.vue')['default']
    Src: typeof import('./src/components/globalComponents1/SvgIcon/src/index.vue')['default']
  }
}
