
services:
  app:
    build:
      context: ./docker-laravel10
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./docker-laravel10/src:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:  php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_meal
      MYSQL_USER: jessie
      MYSQL_PASSWORD: !QAZ1qaz
    ports:
      - "3306:3306"
    volumes:
      - ./docker-laravel10/db_data:/var/lib/mysql

  vue3-app:
    build:
      context: ./vue3-ts-order_meal
      dockerfile: Dockerfile 
    container_name: vue3_web
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./vue3-ts-order_meal/vue-order_meal:/app
      - ./vue3-ts-order_meal/vue-order_meal/node_modules:/app/node_modules
    command: npm run dev -- --host
#    command: tail -f /dev/null
    depends_on:
      - db
